substitutions:
  _PROJECT_ID: $PROJECT_ID

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/${_PROJECT_ID}/fincrm-api'
      - '.'

  # Step 2: Push image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'gcr.io/${_PROJECT_ID}/fincrm-api'

  # Step 3: Patch cloudrun.yaml and deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        sed "s|gcr.io/PROJECT_ID_PLACEHOLDER/fincrm-api|gcr.io/${_PROJECT_ID}/fincrm-api|g" cloudrun.yaml > cloudrun.patched.yaml
        gcloud run services replace cloudrun.patched.yaml --region=europe-west1 --platform=managed
  # Step 4: Allow unauthenticated access
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - run
      - services
      - add-iam-policy-binding
      - fincrm-api
      - --region=europe-west1
      - --member=allUsers
      - --role=roles/run.invoker

images:
  - 'gcr.io/${_PROJECT_ID}/fincrm-api'

timeout: 1200s
