# .cloudbuild.yaml
steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/fincrm-api'
      - '.'

  # Step 2: Push image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'gcr.io/$PROJECT_ID/fincrm-api'

  # Step 3: Deploy to Cloud Run using YAML config
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - run
      - services
      - replace
      - cloudrun.yaml
      - '--region=europe-west1'
      - '--platform=managed'

timeout: 1200s

images:
  - 'gcr.io/$PROJECT_ID/fincrm-api'
